import type { CommunityPost, ServiceOffer } from "../../Api/community.api";

// ── Mock Offers ─────────────────────────────────────
const mockOffers: ServiceOffer[] = [
    {
        id: 1,
        craftsman: {
            id: 101,
            name: "أحمد الصنايعي",
            avatar: "",
            rating: 4.8,
            completed_jobs: 47,
        },
        price: 1500,
        description: "أقدر أنفذ الشغل ده بجودة عالية. عندي خبرة ١٠ سنين في المجال وهبدأ فوراً.",
        delivery_days: 3,
        status: "pending",
        created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 2,
        craftsman: {
            id: 102,
            name: "محمد كهربائي",
            avatar: "",
            rating: 4.5,
            completed_jobs: 32,
        },
        price: 1200,
        description: "هقدر أخلص الشغل في يومين. السعر شامل كل الخامات المطلوبة.",
        delivery_days: 2,
        status: "pending",
        created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 3,
        craftsman: {
            id: 103,
            name: "عمرو السباك",
            avatar: "",
            rating: 4.9,
            completed_jobs: 85,
        },
        price: 1800,
        description: "متخصص في النوع ده من الشغل. هستخدم أفضل الخامات المتاحة وضمان سنة.",
        delivery_days: 4,
        status: "pending",
        created_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    },
];

// ── Mock Posts ───────────────────────────────────────
export const MOCK_POSTS: CommunityPost[] = [
    {
        id: 1,
        title: "تركيب وصلات كهرباء في شقة جديدة - مدينة نصر",
        description: "محتاج كهربائي يركب وصلات كهرباء جديدة في شقة ١٥٠ متر. الشقة لسه تشطيب ومحتاجة توصيلات من الصفر بما فيها اللوحة الرئيسية والأفياش والمفاتيح.",
        category: "electrical",
        budget_min: 2000,
        budget_max: 4000,
        location: "مدينة نصر، القاهرة",
        images: [
            "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600",
            "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600",
        ],
        status: "open",
        user: { id: 1, name: "كريم أحمد", avatar: "", type: "user" },
        offers_count: 3,
        offers: mockOffers,
        comments_count: 2,
        created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
        is_mine: false,
        has_offered: false,
    },
    {
        id: 2,
        title: "إصلاح تسريب مياه في الحمام",
        description: "فيه تسريب مياه من الحنفية الرئيسية في الحمام ومحتاج سباك يكشف ويصلح. المشكلة موجودة من حوالي أسبوع.",
        category: "plumbing",
        budget_min: 500,
        budget_max: 1000,
        location: "المعادي، القاهرة",
        images: [
            "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=600",
        ],
        status: "open",
        user: { id: 2, name: "شركة النور للمقاولات", avatar: "", type: "company" },
        offers_count: 5,
        comments_count: 4,
        created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        is_mine: false,
        has_offered: false,
    },
    {
        id: 3,
        title: "دهان شقة كاملة ٣ غرف وصالة",
        description: "محتاج نقاش يدهن شقة كاملة. ٣ غرف + صالة + مطبخ + ٢ حمام. الشقة ١٢٠ متر. يفضل دهان بلاستيك جوتن أو ما يعادله.",
        category: "painting",
        budget_min: 3000,
        budget_max: 5000,
        location: "الدقي، الجيزة",
        images: [
            "https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=600",
            "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=600",
            "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600",
        ],
        status: "in_progress",
        user: { id: 3, name: "سارة محمود", avatar: "", type: "user" },
        accepted_offer: mockOffers[0],
        offers_count: 7,
        comments_count: 3,
        created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
        is_mine: false,
        has_offered: true,
    },
    {
        id: 4,
        title: "تركيب تكييف سبليت ٢.٢٥ حصان",
        description: "عندي تكييف شارب ٢.٢٥ حصان جديد ومحتاج فني يركبه. الشقة دور خامس وفيه مكان جاهز للوحدة الخارجية.",
        category: "ac",
        budget_min: 400,
        budget_max: 700,
        location: "التجمع الخامس، القاهرة",
        images: [],
        status: "open",
        user: { id: 4, name: "عمر خالد", avatar: "", type: "user" },
        offers_count: 2,
        comments_count: 1,
        created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
        is_mine: false,
        has_offered: false,
    },
    {
        id: 5,
        title: "بناء حائط فاصل في صالة كبيرة",
        description: "محتاج بنّاء يبني حائط طوب فاصل في صالة عرضها ٦ أمتار. الارتفاع ٣ أمتار. محتاج الحائط يكون مع باب.",
        category: "masonry",
        budget_min: 1500,
        budget_max: 3000,
        location: "حلوان، القاهرة",
        images: [
            "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600",
        ],
        status: "completed",
        user: { id: 5, name: "شركة البناء الحديث", avatar: "", type: "company" },
        accepted_offer: mockOffers[2],
        offers_count: 4,
        comments_count: 6,
        created_at: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
        is_mine: false,
        has_offered: false,
    },
    {
        id: 6,
        title: "تصليح باب خشبي وتغيير المفصلات",
        description: "الباب الرئيسي للشقة محتاج تصليح. المفصلات بايظة والباب مش بيقفل كويس. ممكن يحتاج تغيير القفل كمان.",
        category: "carpentry",
        budget_min: 300,
        budget_max: 600,
        location: "شبرا، القاهرة",
        images: [],
        status: "open",
        user: { id: 6, name: "ياسمين علي", avatar: "", type: "user" },
        offers_count: 1,
        comments_count: 0,
        created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
        updated_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
        is_mine: false,
        has_offered: false,
    },
];

// ── Mock Offers for detail page ─────────────────────
export const MOCK_OFFERS = mockOffers;

// ── Mock Comments ───────────────────────────────────
export const MOCK_COMMENTS = [
    {
        id: 1,
        body: "ممكن تبعتلي صور أكتر للمكان عشان أقدر أحدد الخامات المطلوبة",
        user: { id: 101, name: "أحمد الصنايعي", avatar: "", type: "craftsman" },
        created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 2,
        body: "هل المكان فيه كهرباء شغالة ولا محتاج جنيريتور؟",
        user: { id: 102, name: "محمد كهربائي", avatar: "", type: "craftsman" },
        created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    },
];
